version: '2'
services:
  php:
    build:
      context: ./services/php
    volumes:
      - ./app:/app
    environment:
      XDEBUG_CONFIG: "remote_host=10.10.10.1"

  nginx:
    build:
     context: ./services/nginx
    volumes_from:
      - php
    links:
      - php
    ports:
      - 80:80
